print("Loading TurtleControl APIs...")
os.loadAPI("tc/movement")
os.loadAPI("tc/builder")
os.loadAPI("tc/miner")
os.loadAPI("tc/inventory")
os.loadAPI("tc/utils")
os.loadAPI("tc/location")
print("All APIs loaded.")